using System;
using System.Collections.Generic;
using System.Text;

namespace CxAPI_Store.dto
{
    public class MasterDTO
    {
        public long Project_Id { get; set; }
        public long Project_TeamId { get; set; }
        public string Project_Name { get; set; }
        public bool Project_isPublic { get; set; }
        public string Project_sourceSettingsLink_type { get; set; }
        public string Project_sourceSettingsLink_rel { get; set; }
        public string Project_sourceSettingsLink_uri { get; set; }
        public string Project_link_Rel { get; set; }
        public string Project_link_Uri { get; set; }
        public string Project_Team_Name { get; set; }
        public string Project_Preset_Name { get; set; }
        public string Project_engineConfiguration_id { get; set; }
        public string Project_engineConfiguration_Link_rel { get; set; }
        public string Project_engineConfiguration_Link_uri { get; set; }
        public string Project_postScanAction { get; set; }
        public string Project_preset_id { get; set; }
        public string Project_preset_link_rel { get; set; }
        public string Project_preset_link_uri { get; set; }
        public string Project_project_id { get; set; }
        public string Project_project_link_rel { get; set; }
        public string Project_project_link_uri { get; set; }
        public string Project_customFields_0_id { get; set; }
        public string Project_customFields_0_value { get; set; }
        public string Project_customFields_0_name { get; set; }
        public string Project_customFields_1_id { get; set; }
        public string Project_customFields_1_value { get; set; }
        public string Project_customFields_1_name { get; set; }
        public string Project_customFields_2_id { get; set; }
        public string Project_customFields_2_value { get; set; }
        public string Project_customFields_2_name { get; set; }
        public string Project_customFields_3_id { get; set; }
        public string Project_customFields_3_value { get; set; }
        public string Project_customFields_3_name { get; set; }
        public string Project_customFields_4_id { get; set; }
        public string Project_customFields_4_value { get; set; }
        public string Project_customFields_4_name { get; set; }
        public string Project_links_0_rel { get; set; }
        public string Project_links_0_uri { get; set; }
        public string Project_links_0_type { get; set; }
        public string Project_links_1_rel { get; set; }
        public string Project_links_1_uri { get; set; }
        public string Project_links_1_type { get; set; }
        public string Project_links_2_rel { get; set; }
        public string Project_links_2_uri { get; set; }
        public string Project_links_2_type { get; set; }
        public string Project_links_3_rel { get; set; }
        public string Project_links_3_uri { get; set; }
        public string Project_links_3_type { get; set; }
        public string Project_links_4_rel { get; set; }
        public string Project_links_4_uri { get; set; }
        public string Project_links_4_type { get; set; }
        public string Project_links_5_rel { get; set; }
        public string Project_links_5_uri { get; set; }
        public string Project_links_5_type { get; set; }
        public string Summary_Id { get; set; }
        public string Summary_Project_Id { get; set; }
        public string Summary_Project_Name { get; set; }
        public string Summary_Project_Link { get; set; }
        public string Summary_Status_Id { get; set; }
        public string Summary_Status_Name { get; set; }
        public string Summary_Status_Details_Stage { get; set; }
        public string Summary_Status_Details_Step { get; set; }
        public string Summary_ScanType_Id { get; set; }
        public string Summary_ScanType_Value { get; set; }
        public string Summary_Comment { get; set; }
        public DateTime Summary_DateAndTime_StartedOn { get; set; }
        public DateTime Summary_DateAndTime_FinishedOn { get; set; }
        public DateTime Summary_DateAndTime_EngineStartedOn { get; set; }
        public DateTime Summary_DateAndTime_EngineFinishedOn { get; set; }
        public string Summary_ResultsStatistics_Link { get; set; }
        public string Summary_ScanState_Path { get; set; }
        public string Summary_ScanState_SourceId { get; set; }
        public int Summary_ScanState_FilesCount { get; set; }
        public int Summary_ScanState_LinesOfCode { get; set; }
        public int Summary_ScanState_FailedLinesOfCode { get; set; }
        public string Summary_ScanState_CxVersion { get; set; }
        public string Summary_ScanState_LanguageStateCollection_0_LanguageId { get; set; }
        public string Summary_ScanState_LanguageStateCollection_0_LanguageName { get; set; }
        public string Summary_ScanState_LanguageStateCollection_0_LanguageHash { get; set; }
        public string Summary_ScanState_LanguageStateCollection_0_StateCreationDate { get; set; }
        public string Summary_ScanState_LanguageStateCollection_1_LanguageId { get; set; }
        public string Summary_ScanState_LanguageStateCollection_1_LanguageName { get; set; }
        public string Summary_ScanState_LanguageStateCollection_1_LanguageHash { get; set; }
        public string Summary_ScanState_LanguageStateCollection_1_StateCreationDate { get; set; }
        public string Summary_ScanState_LanguageStateCollection_2_LanguageId { get; set; }
        public string Summary_ScanState_LanguageStateCollection_2_LanguageName { get; set; }
        public string Summary_ScanState_LanguageStateCollection_2_LanguageHash { get; set; }
        public string Summary_ScanState_LanguageStateCollection_2_StateCreationDate { get; set; }
        public string Summary_ScanState_LanguageStateCollection_3_LanguageId { get; set; }
        public string Summary_ScanState_LanguageStateCollection_3_LanguageName { get; set; }
        public string Summary_ScanState_LanguageStateCollection_3_LanguageHash { get; set; }
        public string Summary_ScanState_LanguageStateCollection_3_StateCreationDate { get; set; }
        public string Summary_ScanState_LanguageStateCollection_4_LanguageId { get; set; }
        public string Summary_ScanState_LanguageStateCollection_4_LanguageName { get; set; }
        public string Summary_ScanState_LanguageStateCollection_4_LanguageHash { get; set; }
        public string Summary_ScanState_LanguageStateCollection_4_StateCreationDate { get; set; }
        public string Summary_Owner { get; set; }
        public string Summary_Origin { get; set; }
        public string Summary_InitiatorName { get; set; }
        public string Summary_OwningTeamId { get; set; }
        public string Summary_OwningTeam { get; set; }
        public string Summary_IsPublic { get; set; }
        public string Summary_IsLocked { get; set; }
        public string Summary_IsIncremental { get; set; }
        public int Summary_ScanRisk { get; set; }
        public int Summary_ScanRiskSeverity { get; set; }
        public string Summary_EngineServer_Id { get; set; }
        public string Summary_EngineServer_Name { get; set; }
        public string Summary_EngineServer_Link { get; set; }
        public string Summary_FinishedScanStatus_Id { get; set; }
        public string Summary_FinishedScanStatus_Value { get; set; }
        public string Summary_PartialScanReasons { get; set; }
        public int Summary_HighSeverity { get; set; }
        public int Summary_MediumSeverity { get; set; }
        public int Summary_LowSeverity { get; set; }
        public int Summary_InfoSeverity { get; set; }
        public DateTime Summary_StatisticsCalculationDate { get; set; }
        public string Scan_InitiatorName { get; set; }
        public string Scan_Owner { get; set; }
        public long Scan_ScanId { get; set; }
        public long Scan_ProjectId { get; set; }
        public string Scan_ProjectName { get; set; }
        public string Scan_TeamFullPathOnReportDate { get; set; }
        public string Scan_DeepLink { get; set; }
        public DateTime Scan_ScanStart { get; set; }
        public string Scan_Preset { get; set; }
        public string Scan_ScanTime { get; set; }
        public string Scan_LinesOfCodeScanned { get; set; }
        public string Scan_FilesScanned { get; set; }
        public DateTime Scan_ReportCreationTime { get; set; }
        public string Scan_Team { get; set; }
        public string Scan_CheckmarxVersion { get; set; }
        public string Scan_ScanComments { get; set; }
        public string Scan_ScanType { get; set; }
        public string Scan_SourceOrigin { get; set; }
        public string Scan_Visibility { get; set; }
        public long Query_id { get; set; }
        public string Query_categories { get; set; }
        public int Query_cweId { get; set; }
        public string Query_name { get; set; }
        public string Query_group { get; set; }
        public string Query_Severity { get; set; }
        public string Query_Language { get; set; }
        public string Query_LanguageHash { get; set; }
        public string Query_LanguageChangeDate { get; set; }
        public string Query_SeverityIndex { get; set; }
        public string Query_QueryPath { get; set; }
        public string Query_QueryVersionCode { get; set; }
        public long Result_NodeId { get; set; }
        public string Result_FileName { get; set; }
        public string Result_Status { get; set; }
        public string Result_Line { get; set; }
        public string Result_Column { get; set; }
        public string Result_FalsePositive { get; set; }
        public string Result_Severity { get; set; }
        public string Result_AssignToUser { get; set; }
        public int Result_state { get; set; }
        public string Result_Remark { get; set; }
        public string Result_DeepLink { get; set; }
        public string Result_SeverityIndex { get; set; }
        public string Result_DetectionDate { get; set; }
        public long Result_ResultId { get; set; }
        public int Result_PathId { get; set; }
        public long Result_SimilarityId { get; set; }
        public string PathNode_First_FileName { get; set; }
        public int PathNode_First_Line { get; set; }
        public int PathNode_First_Column { get; set; }
        public long PathNode_First_NodeId { get; set; }
        public string PathNode_First_Name { get; set; }
        public string PathNode_First_Type { get; set; }
        public int PathNode_First_Length { get; set; }
        public string PathNode_First_Snippet_Line_Number { get; set; }
        public string PathNode_First_Snippet_Line_Code { get; set; }
        public string PathNode_Last_FileName { get; set; }
        public int PathNode_Last_Line { get; set; }
        public int PathNode_Last_Column { get; set; }
        public int PathNode_Last_NodeId { get; set; }
        public string PathNode_Last_Name { get; set; }
        public string PathNode_Last_Type { get; set; }
        public int PathNode_Last_Length { get; set; }
        public string PathNode_Last_Snippet_Line_Number { get; set; }
        public string PathNode_Last_Snippet_Line_Code { get; set; }
    }


}