sourceSettingsLink.type: Settings.SourceType
sourceSettingsLink.rel: Settings.SourceRel
sourceSettingsLink.uri: Settings.SourceUri
link.Rel: Settings.LinkRel
link.Uri: Settings.LinkUri
isPublic: Settings.IsPublic
engineConfiguration.id: Settings.EngineConfigId
engineConfiguration.Link: Settings.EngineConfigLink
engineConfiguration.Link.uri: Settings.EngineConfigUri
postScanAction: Settings.PostScanAction 
preset.id: Settings.PresetId
preset.link.rel: Settings.PresetRel
preset.link.uri: Settings.PresetUri
project.id: Settings.ProjectId
project.link.rel: Settings.ProjectRel
project.link.uri: Settings.ProjectUri
customFields.0.id: Settings.CustomFields.0.Id
customFields.0.value: Settings.CustomFields.0.Value
customFields.0.name: Settings.CustomFields.0.Name
customFields.1.id: Settings.CustomFields.1.Id
customFields.1.value: Settings.CustomFields.1.Value
customFields.1.name: Settings.CustomFields.1.Name
customFields.2.id: Settings.CustomFields.2.Id
customFields.2.value: Settings.CustomFields.2.Value
customFields.2.name: Settings.CustomFields.2.Name
customFields.3.id: Settings.CustomFields.3.Id
customFields.3.value: Settings.CustomFields.3.Value
customFields.3.name: Settings.CustomFields.3.Name
customFields.4.id: Settings.CustomFields.4.Id
customFields.4.value: Settings.CustomFields.4.Value
customFields.4.name: Settings.CustomFields.4.Name
links.0.rel: Settings.Links.0.Rel
links.0.uri: Settings.Links.0.Uri
links.0.type: Settings.Links.0.Type
links.1.rel: Settings.Links.1.Rel
links.1.uri: Settings.Links.1.Uri
links.1.type: Settings.Links.1.Type
links.2.rel: Settings.Links.2.Rel
links.2.uri: Settings.Links.2.Uri
links.2.type: Settings.Links.2.Type
links.3.rel: Settings.Links.3.Rel
links.3.uri: Settings.Links.3.Uri
links.3.type: Settings.Links.3.Type
links.4.rel: Settings.Links.4.Rel
links.4.uri: Settings.Links.4.Uri
links.4.type: Settings.Links.4.Type
